---
- hosts: localhost
  connection: local
  roles:
    - infra
    
- hosts: etcd_cluster
  gather_facts: yes
  roles:
    - prereq

- hosts: etcd1
  gather_facts: yes
  roles:
    - ca

- hosts: etcd_cluster
  gather_facts: yes
  roles:
    - certstransfer
    - getetcd
    - etcdinstallation

- hosts: localhost
  connection: local
  roles:
    - removelocalfiles